export enum Type {
  FETCH_PROFILE = "FETCH_PROFILE",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  FETCH_PAGE = "FETCH_PAGE",
  FETCH_TOTAL_PAGE="FETCH_TOTAL_PAGE",
  FETCH_APPOINTMENTS="FETCH_APPOINTMENTS",
  SET_PATIENT="SET_PATIENT"
}
